### PR TITLE
Fix master upgrade regressions

### LINKED ISSUE #229: ConfigureMaster#upgrade undefined method `with_tmpfile' for #<Pharos::SSH::Client:0x000000000307fa00>
See https://github.com/kontena/pharos-cluster/pull/222/files#r180750879
Regression from #223 

```
undefined method `with_tmpfile' for #<Pharos::SSH::Client:0x000000000307fa00>
/app/lib/pharos/phases/configure_master.rb:247:in `upgrade'
/app/lib/pharos/phases/configure_master.rb:24:in `call'
/app/lib/pharos/phase_manager.rb:70:in `block in apply'
/app/lib/pharos/phase_manager.rb:40:in `block in run_serial'
/app/lib/pharos/phase_manager.rb:39:in `map'
/app/lib/pharos/phase_manager.rb:39:in `run_serial'
/app/lib/pharos/phase_manager.rb:51:in `run'
/app/lib/pharos/phase_manager.rb:67:in `apply'
/app/lib/pharos/cluster_manager.rb:70:in `apply_phase'
/app/lib/pharos/cluster_manager.rb:51:in `apply_phases'
/app/lib/pharos/up_command.rb:99:in `configure'
/app/lib/pharos/up_command.rb:46:in `block in execute'
/app/lib/pharos/up_command.rb:44:in `chdir'
/app/lib/pharos/up_command.rb:44:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
/app/lib/pharos/root_command.rb:14:in `run'
bin/pharos-cluster:12:in `<main>'
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #229 use of `@ssh.tempfile`

Fixes #111 only upgrade worker node kubelets after master upgrade

### CODE REVIEW

File: lib/pharos/cluster_manager.rb [hunk 1]
```diff
@@ -48,9 +48,8 @@ def apply_phases
       apply_phase(Phases::ValidateHost, config.hosts, ssh: true, parallel: true)
       apply_phase(Phases::ConfigureHost, config.hosts, ssh: true, parallel: true)
 
-      apply_phase(Phases::ConfigureKubelet, config.worker_hosts, ssh: true, parallel: true) # TODO: also run this phase in parallel for the master nodes, if not doing an upgrade?
-
       apply_phase(Phases::ConfigureMaster, config.master_hosts, ssh: true, parallel: false)
+      apply_phase(Phases::ConfigureKubelet, config.worker_hosts, ssh: true, parallel: true) # TODO: also run this phase in parallel for the master nodes, if not doing an upgrade?
```
Comment (SpComb) [inline lib/pharos/cluster_manager.rb]: It doesn't matter which order the kubelets get configured for the initial install, but for the upgrade case, the kubelet ugprade needs to happen after the master node kubeadm upgrade.
