### ISSUE TITLE
ConfigureMaster#upgrade undefined method `with_tmpfile' for #<Pharos::SSH::Client:0x000000000307fa00>

### ISSUE THREAD

**Issue by SpComb** [kontena/pharos-cluster#229]
See https://github.com/kontena/pharos-cluster/pull/222/files#r180750879
Regression from #223 

```
undefined method `with_tmpfile' for #<Pharos::SSH::Client:0x000000000307fa00>
/app/lib/pharos/phases/configure_master.rb:247:in `upgrade'
/app/lib/pharos/phases/configure_master.rb:24:in `call'
/app/lib/pharos/phase_manager.rb:70:in `block in apply'
/app/lib/pharos/phase_manager.rb:40:in `block in run_serial'
/app/lib/pharos/phase_manager.rb:39:in `map'
/app/lib/pharos/phase_manager.rb:39:in `run_serial'
/app/lib/pharos/phase_manager.rb:51:in `run'
/app/lib/pharos/phase_manager.rb:67:in `apply'
/app/lib/pharos/cluster_manager.rb:70:in `apply_phase'
/app/lib/pharos/cluster_manager.rb:51:in `apply_phases'
/app/lib/pharos/up_command.rb:99:in `configure'
/app/lib/pharos/up_command.rb:46:in `block in execute'
/app/lib/pharos/up_command.rb:44:in `chdir'
/app/lib/pharos/up_command.rb:44:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
/app/lib/pharos/root_command.rb:14:in `run'
bin/pharos-cluster:12:in `<main>'
```
